{% set version = "4.2.0" %}

package:
  name: selenium
  version: {{ version }}

source:
  # TODO: simplify after https://github.com/SeleniumHQ/selenium/issues/9917
  - folder: dist
    fn: selenium-{{ version }}.zip
    url: https://files.pythonhosted.org/packages/py3/s/selenium/selenium-{{ version }}-py3-none-any.whl
    sha256: ba5b2633f43cf6fe9d308fa4a6996e00a101ab9cb1aad6fd91ae1f3dbe57f56f
  - folder: src
    url: https://github.com/SeleniumHQ/selenium/archive/refs/tags/selenium-{{ version }}.tar.gz
    sha256: bb0b38c094bc3a9cc05eae30b2293ef18dfc60fb31893295473d4c1218352e97

build:
  noarch: python
  number: 0
  script:
    - cd {{ RECIPE_DIR }} && python copy_wheel.py
    - cd {{ SRC_DIR }}/src/py && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trio
    - trio-websocket
    - urllib3

test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.opera
    - selenium.webdriver.remote
    - selenium.webdriver.support
    - selenium.webdriver.support
  commands:
    - pip check

about:
  home: https://www.selenium.dev
  license_file:
    - src/LICENSE
    - src/NOTICE
  license: Apache-2.0
  summary: Python bindings for the Selenium WebDriver for automating web browser interaction.
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
