{% set version = "4.7.0" %}

package:
  name: selenium
  version: {{ version }}

source:
  # TODO: simplify after https://github.com/SeleniumHQ/selenium/issues/9917
  - folder: dist
    fn: selenium-{{ version }}.zip
    url: https://files.pythonhosted.org/packages/py3/s/selenium/selenium-{{ version }}-py3-none-any.whl
    sha256: 771cb63b821a2aea01b0cdb623caa5b5c35b9a19f44d0d4f32a44b037a324b10
  - folder: src
    url: https://github.com/SeleniumHQ/selenium/archive/refs/tags/selenium-{{ version }}.tar.gz
    sha256: 267f84e5743832f328a03efa159e2fb8e6b79951e5e3e59f491605a2a59f49e8

build:
  noarch: python
  number: 0
  script:
    - cd {{ RECIPE_DIR }} && python copy_wheel.py
    - cd {{ SRC_DIR }}/src/py && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trio >=0.17,<1.0
    - trio-websocket >=0.9,<1.0
    - urllib3 >=1.26,<2.0
    # urllib3[secure]
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0
    - certifi >=2021.10.8
    # urllib3[socks]
    - pysocks >=1.5.6,<2.0,!=1.5.7
test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check

about:
  home: https://www.selenium.dev
  license_file:
    - src/LICENSE
    - src/NOTICE
  license: Apache-2.0
  summary: Python bindings for the Selenium WebDriver for automating web browser interaction.
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
