{% set version = "4.26.1" %}

package:
  name: selenium
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/s/selenium/selenium-{{ version }}.tar.gz
    sha256: 7640f3f08ae7f4e450f895678e8a10a55eb4e4ca18311ed675ecc4684b96b683
    patches:
      - 0000-no-rust-setup.patch
  - fn: LICENSE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/LICENSE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/LICENSE
    sha256: de658a7d3761e92b471e2f630ea99eeb3389b27820809b1e4853baabd5fbadb7
  - fn: NOTICE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/NOTICE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/NOTICE
    sha256: 2a3429f61e1ad70d33a6fa517cb46ec183c0b0fbcce34a2183d4c56bea3c874e

build:
  noarch: python
  number: 0
  script:
    - |-
      {{ PYTHON }} -c "c = __import__('pathlib').Path('selenium/webdriver/common'); [(print(b), b.unlink()) for b in c.glob('*/selenium-manager*')]"
    - |
      {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - certifi >=2021.10.8
    - python >=3.8
    - selenium-manager {{ version.split('.')[:2] | join('.') }}.*
    - trio >=0.17,<1.0
    - trio-websocket >=0.9,<1.0
    - typing_extensions >=4.9,<5.0
    - urllib3 >=1.26,<3
    - websocket-client >=1.8,<2.0
test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver.common
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check
    - python -c "from selenium.webdriver.common.selenium_manager import SeleniumManager; assert SeleniumManager._get_binary().exists()"

about:
  home: https://www.selenium.dev
  license_file:
    - LICENSE-selenium-{{ version }}
    - NOTICE-selenium-{{ version }}
  license: Apache-2.0
  summary: Official Python bindings for Selenium WebDriver
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
