{% set version = "4.7.2" %}

package:
  name: selenium
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
    sha256: 3aefa14a28a42e520550c1cd0f29cf1d566328186ea63aa9a3e01fb265b5894d
  - fn: LICENSE-selenium-{{ version }}
    url: https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/LICENSE
    sha256: 7f88ada9fb6ad60f88d72973ed120391a3c2886a84543829e3b8780e5421b85d
  - fn: NOTICE-selenium-{{ version }}
    url: https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/NOTICE
    sha256: ca069b5b2f54e3cdf9d3145dc4977b86cf4b6481539f6eb6449a2903d0e016a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trio >=0.17,<1.0
    - trio-websocket >=0.9,<1.0
    - urllib3 >=1.26,<2.0
    - certifi >=2021.10.8
test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check

about:
  home: https://www.selenium.dev
  license_file:
    - LICENSE-selenium-{{ version }}
    - NOTICE-selenium-{{ version }}
  license: Apache-2.0
  summary: Python bindings for the Selenium WebDriver for automating web browser interaction.
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
